[package]
name = "dash-shell"
version = "0.1.0"
edition = "2021"
description = "Dustin's Awesome Shell Handler"
license = "GPL-3.0-only"
readme = "./readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "*"
